sudo: required
services:
  - docker

before_install:
  - docker build -t cinqjoy/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cinqjoy/react-test npm test

after_success:
  - docker build -t cinqjoy/multi-client ./client
  - docker build -t cinqjoy/multi-nginx ./nginx
  - docker build -t cinqjoy/multi-server ./server
  - docker build -t cinqjoy/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push cinqjoy/multi-client
  - docker push cinqjoy/multi-nginx
  - docker push cinqjoy/multi-server
  - docker push cinqjoy/multi-worker
